import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Album } from '../components/Album'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>KageNet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to KageNet.
        </h1>

        <p className={styles.description}>
          Can you guess the correct genre?
        </p>
          <Album/>
      </main>

      <footer className={styles.footer}>
        <p>
          Any questions or suggestions? Contact us at <a className={styles.email} href="mailto: placeholder@itu.dk">placeholder@itu.dk</a>
        </p>
      </footer>
    </div>
  )
}
